In [1]:
import numpy as np


In [7]:
#1. Create a NumPy array containing numbers from 1 to 10.
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
#2. Create an array of 5 zeros.
import numpy as np
array = np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


In [14]:
#3.create an array of 5 ones
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [19]:
#4. Create an array containing only even numbers from 2 to 20.
arr = np.arange(2,21,2)
print(arr)



[ 2  4  6  8 10 12 14 16 18 20]


In [20]:
#5. Find the shape of a given array.
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


In [22]:
#6. find the number of elements in an array
array = [1,2,3,4,5,6,7]
print(arr.size)

6


In [23]:
#7. Access the first, last, and third element of an array.
arr = np.array([10,20,30,40,50,60])
print(arr[0])
print(arr[-1])
print(arr[-2])

10
60
50


In [26]:
#8. Change a specific element in an array.

arr = np.array([1,2,3,4,5,6,6])
arr[2] = 100
print(arr)

[  1   2 100   4  56   6]


In [27]:
#9. Create a 3x3 matrix filled with zeros.
matrix = np.zeros((3,3))
print(matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
#10. Create a 4x4 matrix filled with ones.
matrix = np.ones((4,4))
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
#11. Create a 5x5 identity matrix
matrix = np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
#12. Generate 10 random integers between 1 and 100.
arr= np.random.randint(1,101, 10)
print(arr)

[49 55 77 14 79 76 52 51 21 55]


In [33]:
#13. Find the maximum and minimum values in an array

In [34]:
arr = np.array([10,50,20,80,5])

print(np.max(arr))
print(np.min(arr))

80
5


In [36]:
#14. Calculate the sum of all elements in an array.
arr = [2,3,4,5,6,7]
print(np.sum(arr))

27


In [37]:
#15. Calculate the average (mean) of an array.
arr = [2,3,4,5,6,78,8]
print(np.mean(arr))

15.142857142857142


In [38]:
#16. Sort an array in ascending order.
arr = [1,6,4,8,4,9,3]
print(np.sort(arr))

[1 3 4 4 6 8 9]


In [39]:
#17. Reverse an array.
arr = [1,6,4,8,4,9,3]
print(arr[::1])

[1, 6, 4, 8, 4, 9, 3]


In [40]:
#18. Find all elements greater than 50.
arr = np.array([10,60,70,20,80])

print(arr[arr > 50])

[60 70 80]


In [41]:
#19. Count occurrences of a value in an array.

In [42]:
arr = np.array([1,2,3,2,2,5])

print(np.count_nonzero(arr == 2))

3


In [43]:
#20. Reshape an array of 12 elements into a 3x4 matrix.
arr = np.arange(1,13)

matrix = arr.reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
